# Server
server.port=8081

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_facility_db
spring.datasource.username=postgres
spring.datasource.password=HNR2026416
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=smart-facility-app

# Temporarily disable security so we can test endpoints without login
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

